--- #YAML:1.0
name: Net-OpenDHT
version: 0.33
author:
  - Leon Brocard <acme@astray.com>.
abstract: Access the Open Distributed Hash Table (Open DHT)
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
